### ISSUE TITLE
memoryerror

### ISSUE THREAD

**Issue by Tanying1219** [yichen0831/opencc-python#24]
请问出现这个是什么问题？感谢
python -m opencc -i wiki.zh.text -o wiki.zh.text.jian -c t2s
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\lib\site-packages\opencc\__main__.py", line 41, in <module>
    sys.exit(main())
  File "D:\ProgramData\Anaconda3\lib\site-packages\opencc\__main__.py", line 31, in main
    input_str = f.read()
  File "D:\ProgramData\Anaconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError

**Comment by Hopkins1** [comment]
How big was the input file size wiki.zh.text?
