### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by david30907d** [yichen0831/opencc-python#4]
感謝大大的專案
不過pip安裝噴錯了
在此附上錯誤訊息
```
root@b1dcb7389a1f:/code# pip3 install opencc-python-reimplemented
Collecting opencc-python-reimplemented
  Using cached opencc-python-reimplemented-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-a4wg0psa/opencc-python-reimplemented/setup.py", line 7, in <module>
        with open(path.join(cwd, 'README.md'), encoding='utf-8') as f:
      File "/usr/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-a4wg0psa/opencc-python-reimplemented/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a4wg0psa/opencc-python-reimplemented/

```

**Comment by yichen0831** [comment]
I added the README.md file to the package. And the package version is now 0.1.1.
